alias: Washingmachine busy
trigger:
  - platform: numeric_state
    entity_id: sensor.tvattmaskin_power_9_8
    above: 200
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.washingmachine_busy