alias: lights off in walk in closet 2 minutes after last movement
trigger:
  platform: state
  entity_id: switch.walk_in_closet_motion_sensor
  to: 'off'
  for:
    minutes: 2
action:
  service: homeassistant.turn_off
  entity_id: switch.closet_spotlights