alias: "lights off in kitchen 10 minutes after last movement"
trigger:
  platform: state
  entity_id: switch.kitchen_motion_sensor
  to: 'off'
  for:
    minutes: 10
action:
  service: homeassistant.turn_off
  entity_id: switch.kitchen_bench