alias: Kylskap to warm
trigger:
  - platform: numeric_state
    entity_id: sensor.kylskap_temperature
    above: 14
action:
  service: notify.pushbullet
  data_template:
    title: 'Kylskapet ar for varmt'
    target: 'device/Samsung'
    message: "Temp:  {{ states.sensor.kylskap_temperature.state }}  grader."