alias: "bedroom curtains up after 11:00 on weekends"
trigger:
  platform: time
  after: '11:00:00'
condition:
- condition: time
  weekday:
    - sat
    - sun
action:
  - service: cover.open_cover
    data:
      entity_id: cover.bedroom_curtains
