alias: "Transformer battery above 99"
trigger:
  platform: numeric_state
  entity_id: sensor.transformerbattery
  above: 99
action:
  service: homeassistant.turn_off
  entity_id: switch.transformer_charger