alias: ESXi Status
trigger:
  - platform: state
    entity_id: device_tracker.708bcda3b360
    from: 'home'
    to: 'not_home'
action:
  service: notify.facebook
  data: 
    message: "ESXi Offline"
    target:
      - '0046729744201'
