alias: "Magnet sensor front door off"
trigger:
  platform: state
  entity_id: binary_sensor.frontdoor_sensor_19_0
  to: 'off'
  for:
    minutes: 3
action:
  service: homeassistant.turn_off
  entity_id: switch.hallway_roof