alias: frys to cold
trigger:
  - platform: numeric_state
    entity_id: sensor.frys_temperature
    below: -21
action:
  service: notify.pushbullet
  data_template:
    message: "frysen ar for kall, Temp:  {{ states.sensor.frys_temperature.state }}  grader."
    target:
      - '0046729744201'
