alias: Frys to warm
trigger:
  - platform: numeric_state
    entity_id: sensor.frys_temperature
    above: -15
action:
  service: notify.facebook
  data:
    message: "frysen ar för varm, Temp:  {{ states.sensor.frys_temperature.state }}  grader."
    target:
      - '0046729744201'