alias: "Turn off front door automation on movement"
trigger:
  platform: state
  entity_id: binary_sensor.hall_sensor_4_0
  to: 'on'
action:
  service: automation.turn_off
  entity_id: automation.magnet_sensor_front_door_on