alias: Kylskap to cold
trigger:
  - platform: numeric_state
    entity_id: sensor.kylskap_temperature
    below: 5
action:
  service: notify.facebook
  data: 
    message: "Temp:  {{ states.sensor.kylskap_temperature.state }}  grader."
    target:
      - '0046729744201'