alias: Kylskap to cold
trigger:
  - platform: numeric_state
    entity_id: sensor.kylskap_temperature
    below: 5
action:
  service: notify.pushbullet
  data_template: 
    title: 'Kylskapet ar for kallt'
    target: 'device/Samsung'
    message: "Temp:  {{ states.sensor.kylskap_temperature.state }}  grader."