alias: lights off in walk in closet 30 seconds after last movement
trigger:
  platform: state
  entity_id: switch.walk_in_closet_motion_sensor
  to: 'off'
  for:
    seconds: 30
action:
  service: homeassistant.turn_off
  entity_id: switch.walkincloset_spotlights