alias: rTorrent status
trigger:
  - platform: state
    entity_id: device_tracker.rtorrent
    from: 'home'
    to: 'not_home'
action:
  service: notify.facebook
  data:
    message: "Rtorrent Offline, the VPN has disconnected"
    target:
      - '0046729744201'