alias: Server to warm
trigger:
  - platform: numeric_state
    entity_id: sensor.server_temperature
    above: 35
action:
  service: notify.facebook
  data_template:
    message: "Servern är för varm, Temp:  {{ states.sensor.server_temperature.state }}  grader."
    target:
      - '0046729744201'