alias: lights off in the toilet 30 seconds after last movement
trigger:
  platform: state
  entity_id: binary_sensor.toalett_sensor_24_0
  to: 'off'
  for:
    seconds: 30
action:
  service: homeassistant.turn_off
  entity_id: light.toalett