alias: "lights on in the toilet when motion sensor triggers daytime"
trigger:
  platform: state
  entity_id: binary_sensor.toalett_sensor_24_0
  to: 'on'
condition:
  condition: time
  after: '18:00:00'
  before: '08:00:00'
action:
  service: scene.turn_on
  entity_id: scene.toalett_nighttime