alias: "lights on in walk in closet when motion sensor triggers"
trigger:
  platform: state
  entity_id: binary_sensor.walkincloset_sensor_21_0
  to: 'on'
condition:
  condition: state
  entity_id: sun.sun
  state: 'below_horizon'
action:
  service: homeassistant.turn_on
  entity_id: switch.walkincloset_spotlights