alias: "lights on in walk in closet when motion sensor triggers"
trigger:
  platform: state
  entity_id: binary_sensor.walkincloset_sensor_21_0
  to: 'on'
condition:
  condition: time
  after: '18:00:00'
  before: '08:00:00'
action:
  service: homeassistant.turn_on
  entity_id: switch.sonoff2