alias: 'Washer Start'
trigger:
  platform: state
  entity_id: sensor.washer_pwrdn
  from: 'True'
  to: 'False'
action:
  service: input_boolean.turn_on
  entity_id: input_boolean.washer_switch