alias: 'Washer Done'
trigger:
  platform: state
  entity_id: sensor.washer_pwrdn
  from: 'False'
  to: 'True'
  for:
    minutes: 3
condition:
    condition: state
    entity_id: input_boolean.washer_switch
    state: 'on'
action:
  - service: notify.facebook
    data:
      message: 'Nu är tvätten klar!'
      target:
        - '0046729744201'
        - '0046735166707'
  - service: homeassistant.turn_off
    entity_id: input_boolean.washer_switch